// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsUn0rNaYlHbZxMU-GeG5SyWfocJ6EK-E',
    appId: '1:34512832689:web:28d823277d20836c4bba90',
    messagingSenderId: '34512832689',
    projectId: 'firechat-e0fb7',
    authDomain: 'firechat-e0fb7.firebaseapp.com',
    storageBucket: 'firechat-e0fb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_fgFGvD5KXbF4rXQAFfrtb2aK5VMCHU',
    appId: '1:34512832689:android:0356cda16db055e84bba90',
    messagingSenderId: '34512832689',
    projectId: 'firechat-e0fb7',
    storageBucket: 'firechat-e0fb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDON6fNN3Pl-OuB3w8X1sKsaYu84APleC4',
    appId: '1:34512832689:ios:c845c1597b46df914bba90',
    messagingSenderId: '34512832689',
    projectId: 'firechat-e0fb7',
    storageBucket: 'firechat-e0fb7.appspot.com',
    iosBundleId: 'com.example.fireChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDON6fNN3Pl-OuB3w8X1sKsaYu84APleC4',
    appId: '1:34512832689:ios:107ee00c010f39084bba90',
    messagingSenderId: '34512832689',
    projectId: 'firechat-e0fb7',
    storageBucket: 'firechat-e0fb7.appspot.com',
    iosBundleId: 'com.example.fireChatApp.RunnerTests',
  );
}
